#006 | fail release step if not successful response from heroku

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -30,7 +30,7 @@ jobs:
             docker tag lilyevans/chore-chart:$CIRCLE_SHA1 registry.heroku.com/chore-chart-test/web
             docker push registry.heroku.com/chore-chart-test/web
             DOCKER_IMAGE_ID=$(docker inspect registry.heroku.com/chore-chart-test/web --format={{.Id}})
-            curl -n -X PATCH https://api.heroku.com/apps/chore-chart-test/formation \
+            RELEASE_RESPONSE=$(curl -n -X PATCH https://api.heroku.com/apps/chore-chart-test/formation \
               -d '{
               "updates": [
                 {
@@ -41,7 +41,12 @@ jobs:
             }' \
               -H "Content-Type: application/json" \
               -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
-              -H "Authorization: Bearer "$HEROKU_API_KEY""
+              -H "Authorization: Bearer "$HEROKU_API_KEY"" | jq '.[0].app.name')
+            if [ "$RELEASE_RESPONSE" != "chore-chart-test" ]; then
+              echo "Error: Failed to release new docker image to Heroku"
+              exit 1
+            fi
+
 
 workflows:
   version: 2
